In [1]:
import numpy as np

In [7]:
a = np.array([[1,6],
                [2,8],
                [3,11],
                [3,10],
                [1,7]])

In [8]:
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [9]:
mean_a = np.mean(a, axis=0)

In [10]:
mean_a

array([2. , 8.4])

In [17]:
a_centered = a - mean_a

In [23]:
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

In [26]:
a_centered_sp = a_centered[0: , 0:1] * a_centered[0: , 1:]

In [27]:
a_centered_sp

array([[ 2.4],
       [-0. ],
       [ 2.6],
       [ 1.6],
       [ 1.4]])

In [28]:
a_centered_sp/5

array([[ 0.48],
       [-0.  ],
       [ 0.52],
       [ 0.32],
       [ 0.28]])